/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;

import java.io.IOException;

public class App extends Application {
    private Stage primaryStage;
    private AnchorPane rootLayout;

    public void start(Stage primaryStage){
        this.primaryStage = primaryStage;
        this.primaryStage.setTitle("Flooding");
        initRootLayout();
    }

    public void initRootLayout() {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("/view/MatrixPane.fxml"));
        try {
            rootLayout = loader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }
        Scene scene = new Scene(rootLayout);
        primaryStage.setScene(scene);
        loader.getController();
        primaryStage.show();
    }
}
